ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.2

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    two_d_mode: true

    odometry0: /odom
    odometry0_config: [true,  true,  false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]

    imu0: /imu/data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, true,
                  false, false, false]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
